stages:
  - build

build-asset:
  stage: build
  image: node:18-alpine
  only:
    - master
    - develop
    - tags
  tags:
    - fokus-runner
  script:
    - npm i -g pnpm
    - pnpm install
    - cp .env.template .env.local
    - pnpm run build-only
  artifacts:
    paths:
      - dist

build-and-push:
    stage: build
    image: docker:stable
    services:
      - docker:dind
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE:test-$CI_COMMIT_SHA
    before_script:
      - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    script:
      - docker build -t $IMAGE_NAME .
      - docker push $IMAGE_NAME
    dependencies:
      - build-asset
    tags:
      - fokus-runner
    rules:
      - if: '$CI_COMMIT_BRANCH == "test-ci"'
