stages:
  - build

build-asset:
  stage: build
  image: node:18-alpine
  only:
    - master
    - develop
    - tags
  tags:
    - fokus-runner
  script:
    - npm i -g pnpm
    - pnpm install
    - cp .env.template .env.local
    - pnpm run build-only
  artifacts:
    paths:
      - dist
