stages:
  - build

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store
    - node_modules/
  policy: pull-push

build-asset:
  stage: build
  image: node:18-alpine
  cache:
    <<: *global_cache
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG'
  tags:
    - fokus-runner  # Instead of fokus-runner
  before_script:
    - npm i -g pnpm
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - cp .env.template .env.local
    - pnpm run build-only
  artifacts:
    paths:
      - dist

build-and-push:
    stage: build
    image: docker:stable
    services:
      - docker:dind
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE:test-$CI_COMMIT_SHA
    before_script:
      - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    script:
      - docker build -t $IMAGE_NAME .
      - docker push $IMAGE_NAME
    dependencies:
      - build-asset
    tags:
      - fokus-runner  # Instead of fokus-runner
    rules:
      - if: '$CI_PIPELINE_SOURCE == "web"'
        when: manual
      - if: '$CI_COMMIT_BRANCH == "test-ci"'
