<template>
  <Story
    group="top"
    docs-only
    icon="carbon:bookmark"
  />
</template>

<docs lang="md">
# Welcome

Component stories are a great way to showcase your components. You can use them to show how your components look and behave with different props.

Useful for

- 📃 Organizing and documenting components
- 🧪 Interactive playground for your components in isolation
- 🖼️ Showcasing components to other developers

## Technology Stack

- [Vue 3](https://vuejs.org/) components
- [Tailwind CSS](https://tailwindcss.com/) as base styling framework
- [Taliwind CSS Preset for PrimeVue](https://tailwind.primevue.org/) in unstyled mode as convenient starting point to create custom component library
- [Phosphor Icons](https://icon-sets.iconify.design/ph/) powered by Iconify
- [Histoire](https://histoire.dev/) for generating this page

---

This page was generated by Histoire.
Learn more about Histoire [here](https://histoire.dev/).
</docs>
